project_id: '747375'
api_token: e0bd15e8843d54e30584b1af798502095d4ef1ffee54336f814a98e39f1c333c7da7a82bfd11c456
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /packages/i18n/resources/en/*.json
    translation: /packages/i18n/resources/%two_letters_code%/%original_file_name%
