import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/lego-ui/css/globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap', // Optimize font loading
  preload: true,   // Ensure font is preloaded
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Add viewport metadata for better mobile experience
  viewport: {
    width: 'device-width',
    initialScale: 1,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
